FROM rust:1.70 as builder

WORKDIR /usr/src/

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler cmake

COPY . .

RUN cargo build --release --bin certificate_authority

# --------------

FROM debian:buster-slim

WORKDIR /usr/src/

COPY --from=builder /usr/src/target/release/certificate_authority .

RUN mkdir /usr/src/certificates

EXPOSE 80

VOLUME [ "/usr/src/certificates" ]

CMD ["./certificate_authority"]
