FROM rust:1.70 as builder

WORKDIR /usr/src/

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler cmake

COPY . .

RUN cargo build --release --bin server

FROM debian:buster-slim

WORKDIR /usr/src/

COPY --from=builder /usr/src/target/release/server .

EXPOSE 5545

CMD ["./server"]
